# Generated by Django 3.2.4 on 2021-07-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20210704_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(height_field=200, upload_to='category', width_field=200),
        ),
    ]
